### PR TITLE
Support multiple indexes for same hash

### PR DESCRIPTION
**Pull request by krumft**
This should fix https://github.com/oguimbal/pg-mem/issues/331

### CODE REVIEW

**Review by brunosilvafreitas — APPROVED** [review]

**Comment by zookatron** [comment]
What is blocking this from being merged?

**Review by oguimbal — APPROVED** [review]
thanks, sorry for the delay, i'll release that shortly !

**Comment by oguimbal** [comment]
released as `pg-mem@2.7.0`

**Comment by krumft** [comment]
Thank you so much!

**Pull request merged**
