### PR TITLE
Version upgrades, add type aliases

### PR DESCRIPTION
**Pull request by secam**
- Upgraded dependencies for knex, mikro-orm, typescript, immutable...
- Changed imports to work with new versions 
- upgraded parser to 12.0.1 (removed set names hack)
- Added type aliases for setial8 and int8
- Added test for string insert into bigint columns (mikro-orm does this)
- Added alter enum support

### CODE REVIEW

**Comment by oguimbal** [comment]
Hi, I think this PR will have a lot of conflicts with #351  ...  @knixeur @secam  how would you like to proceed ?
Can your merge both PRs in a single PR ? Or should I merge one of those and you'll handle conflicts in the other ? In that case, which one do you prefer I merge first ?

**Comment by secam** [comment]
I think all the stuff from #351 should be skipped if we merge this. Beause #351 also upgrades mikro-orm but reimplementing workaround, that is completely removed in this PR

**Comment by knixeur** [comment]
Sure go ahead, I'll close mine :+1:

**Review by oguimbal — APPROVED** [review]

**Comment by oguimbal** [comment]
released as `pg-mem@2.8.1` thanks for this nice PR @secam !

**Pull request merged**
