### PR TITLE
Handle the case if we set a timestamp field default to current time

### PR DESCRIPTION
**Pull request by mmcomp**

### CODE REVIEW

**Comment by oguimbal** [comment]
ah, and it would be nice to have a unit test that demonstrate what you are trying to solve (and prevent regressions in the future 😉)

**Comment by abenhamdine** [comment]
Looks like the actual change is limited to these 2 lines : 

image

@mmcomp perhaps you can submit only this change and a unit test ?

**Comment by Thore1954** [comment]
Nice eye @abenhamdine, but I don't understand the point of it anyway.
If they mean something like `"myColumn" timestamp default now()` then it already works.

**Comment by abenhamdine** [comment]
> Nice eye @abenhamdine, but I don't understand the point of it anyway.
> If they mean something like "myColumn" timestamp default now() then it already works

Actually I don't know if this change is needed, I was just asking for adding a test.
If this change is controversial, then a first PR should demonstrate the bug by adding a failing test.

**Pull request closed without merging**
