### PR TITLE
fix: constrain sequelize < 6.20.0

### PR DESCRIPTION
**Pull request by gthb**
Sequelize 6.20.0 breaks a test in pg-mem, so tighten the version constraint to require sequelize < 6.20.0.

The test breakage is:

```
  727 passing (4s)
  25 pending
  1 failing

  1) Sequelize
       can perform sample with force sync:
     relation "table_constraints" does not exist

🐜 This seems to be an execution error, which means that your request syntax seems okay,
    but the resulting statement cannot be executed → Probably not a pg-mem error.

*️⃣ Failed SQL statement: SELECT DISTINCT tc.constraint_name as constraint_name, tc.constraint_schema as constraint_schema, tc.constraint_catalog as constraint_catalog, tc.table_name as table_name,tc.table_schema as table_schema,tc.table_catalog as table_catalog,tc.initially_deferred as initially_deferred,tc.is_deferrable as is_deferrable,kcu.column_name as column_name,ccu.table_schema  AS referenced_table_schema,ccu.table_catalog  AS referenced_table_catalog,ccu.table_name  AS referenced_table_name,ccu.column_name AS referenced_column_name FROM information_schema.table_constraints AS tc JOIN information_schema.key_column_usage AS kcu ON tc.constraint_name = kcu.constraint_name JOIN information_schema.constraint_column_usage AS ccu ON ccu.constraint_name = tc.constraint_name WHERE constraint_type = 'FOREIGN KEY' AND tc.table_name = 'Users';

👉 You can file an issue at https://github.com/oguimbal/pg-mem along with a way to reproduce this error (if you can), and  the stacktrace:

  Error:
      at Query.run (node_modules/sequelize/src/dialects/postgres/query.js:76:25)
      at /Users/gthb/git/pg-mem/node_modules/sequelize/src/sequelize.js:641:28
      at PostgresQueryInterface.getForeignKeyReferencesForTable (node_modules/sequelize/src/dialects/postgres/query-interface.js:161:20)
      at Sequelize.drop (node_modules/sequelize/src/sequelize.js:936:27)
      at Sequelize.sync (node_modules/sequelize/src/sequelize.js:798:7)
      at Object.sequelizeSample (samples/sequelize/sequelize.ts:32:5)
      at Context.<anonymous> (src/tests/sequelize-real.spec.ts:10:9)
```

### CODE REVIEW

**Comment by gthb** [comment]
(Alternatively you could fix the breakage of course — that's a little more time investment than I can afford :) )

**Comment by oguimbal** [comment]
Hi ! 

Thanks for this PR.
I've added the `table_constraints` table... (like most other introspection tables, it will always be empty, though, but that should be OK when you are bootstraping an empty schema for tests !)

👉 Could you test that it works in `pg-mem@2.4.4` without this PR ?  (if it does, I will close this PR)

**Comment by gthb** [comment]
> 👉 Could you test that it works in `pg-mem@2.4.4` without this PR ? (if it does, I will close this PR)

It looks like it does not; see https://github.com/oguimbal/pg-mem/pull/230 where I ran `npm audit fix` which pulls in the latest in-range version of `sequelize`, and that still causes this problem.

**Comment by gthb** [comment]
> > 👉 Could you test that it works in `pg-mem@2.4.4` without this PR ? (if it does, I will close this PR)
> 
> It looks like it does not; see #230 where I ran `npm audit fix` (on the tip of `master` just now) which pulls in the latest in-range version of `sequelize`, and that still causes this problem.

Oh, I see why: `table_constraints` belongs in `information_schema`, not in `pg_catalog`. Fixed that in #231, but then the same test fails because that same query apparently also requires the view `information_schema.key_column_usage`:
```
  1) Sequelize
       can perform sample with force sync:
     relation "key_column_usage" does not exist

🐜 This seems to be an execution error, which means that your request syntax seems okay,
    but the resulting statement cannot be executed → Probably not a pg-mem error.

*️⃣ Failed SQL statement: SELECT DISTINCT tc.constraint_name as constraint_name, tc.constraint_schema as constraint_schema, tc.constraint_catalog as constraint_catalog, tc.table_name as table_name,tc.table_schema as table_schema,tc.table_catalog as table_catalog,tc.initially_deferred as initially_deferred,tc.is_deferrable as is_deferrable,kcu.column_name as column_name,ccu.table_schema  AS referenced_table_schema,ccu.table_catalog  AS referenced_table_catalog,ccu.table_name  AS referenced_table_name,ccu.column_name AS referenced_column_name FROM information_schema.table_constraints AS tc JOIN information_schema.key_column_usage AS kcu ON tc.constraint_name = kcu.constraint_name JOIN information_schema.constraint_column_usage AS ccu ON ccu.constraint_name = tc.constraint_name WHERE constraint_type = 'FOREIGN KEY' AND tc.table_name = 'Users';

👉 You can file an issue at https://github.com/oguimbal/pg-mem along with a way to reproduce this error (if you can), and  the stacktrace:


  Error:
      at Query.run (node_modules/sequelize/src/dialects/postgres/query.js:76:25)
      at /Users/gthb/git/pg-mem/node_modules/sequelize/src/sequelize.js:641:28
      at PostgresQueryInterface.getForeignKeyReferencesForTable (node_modules/sequelize/src/dialects/postgres/query-interface.js:161:20)
      at Sequelize.drop (node_modules/sequelize/src/sequelize.js:936:27)
      at Sequelize.sync (node_modules/sequelize/src/sequelize.js:798:7)
      at Object.sequelizeSample (samples/sequelize/sequelize.ts:32:5)
      at Context.<anonymous> (src/tests/sequelize-real.spec.ts:10:9)
```

**Comment by gthb** [comment]
The query also requires the view constraint_column_usage. Here it is pretty-printed:
```sql
SELECT DISTINCT
  tc.constraint_name as constraint_name,
  tc.constraint_schema as constraint_schema,
  tc.constraint_catalog as constraint_catalog,
  tc.table_name as table_name,
  tc.table_schema as table_schema,
  tc.table_catalog as table_catalog,
  tc.initially_deferred as initially_deferred,
  tc.is_deferrable as is_deferrable,
  kcu.column_name as column_name,
  ccu.table_schema AS referenced_table_schema,
  ccu.table_catalog AS referenced_table_catalog,
  ccu.table_name AS referenced_table_name,
  ccu.column_name AS referenced_column_name
FROM
  information_schema.table_constraints AS tc
  JOIN information_schema.key_column_usage AS kcu ON tc.constraint_name = kcu.constraint_name
  JOIN information_schema.constraint_column_usage AS ccu ON ccu.constraint_name = tc.constraint_name
WHERE
  constraint_type = 'FOREIGN KEY'
  AND tc.table_name = 'Users';
```

**Comment by oguimbal** [comment]
nb: I've added `constraint_column_usage` as well (in `pg-mem@2.6.0` )

**Pull request merged**
